
os: Visual Studio 2015
environment:
  VisualStudioVersion: 14.0
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-$(appveyor_repo_commit)"
before_build:
  - cmd: >-
      dotnet restore
  - ps: >-
      (Get-Content src\Mandrill.net\project.json).replace('"version": "1.0.0-*",', '"version": "' + $env:APPVEYOR_BUILD_VERSION + $env:PRERELEASE_TAG +'",') | Set-Content src\Mandrill.net\project.json
build: off
build_script:
  - dotnet pack src/Mandrill.net --configuration Release --output artifacts
test: off
test_script:
  - cd ./tests/Tests
  - if defined APPVEYOR_PULL_REQUEST_NUMBER dotnet run -f net45 --labels=All --verbose --where:cat!=integration
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER dotnet run -f net45 --labels=All --verbose --where:cat!=exports
  - if defined APPVEYOR_PULL_REQUEST_NUMBER dotnet run -f netcoreapp1.0 --labels=All --verbose --where:cat!=integration
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER dotnet run -f netcoreapp1.0 --labels=All --verbose --where:cat!=exports
artifacts:
  - path: artifacts\**\*.nupkg
deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: yYZGBnyhi9s3qBjVh9KhSnneM/qVxkGiSfNkXWekPyMFSFbDYYoXiuZxwMAQm8YV
  skip_symbols: true
  artifact: /.*\.nupkg/
