//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;event&quot;: &quot;send&quot;,
        ///    &quot;msg&quot;: {
        ///      &quot;ts&quot;: 1365109999,
        ///      &quot;subject&quot;: &quot;This an example webhook message&quot;,
        ///      &quot;email&quot;: &quot;example.webhook@mandrillapp.com&quot;,
        ///      &quot;sender&quot;: &quot;example.sender@mandrillapp.com&quot;,
        ///      &quot;tags&quot;: [
        ///        &quot;webhook-example&quot;
        ///      ],
        ///      &quot;opens&quot;: [],
        ///      &quot;clicks&quot;: [],
        ///      &quot;state&quot;: &quot;sent&quot;,
        ///      &quot;metadata&quot;: {
        ///        &quot;user_id&quot;: 111
        ///      },
        ///      &quot;_id&quot;: &quot;fa239ebedd0a4831a3eefa59e880d8b2&quot;,
        ///      &quot;_version&quot;: &quot;exampleaaaaaaaaaaaaaaa&quot;
        ///    },
        ///    &quot;_id&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mandrill_webhook_example_json {
            get {
                return ResourceManager.GetString("mandrill_webhook_example.json", resourceCulture);
            }
        }
    }
}
